### ISSUE TITLE
Enhance UI and Parameters Management

### ISSUE THREAD

**Issue by Stockless** [JuliaHealth/KomaMRI.jl#524]
### Feature Request

This issue aims to improve the user interface and streamline workflow to enhance usability and ensure consistency in the simulation and reconstruction processes. The tasks focus on better parameter management, flexibility, and presentation enhancements.

**TASKS**
- [ ] Resize collaborators display
- [ ] Display default simulation parameters before simulation
- [ ] Display default reconstruction parameters before reconstruction and after simulation
- [ ] Allow modification of simulation and reconstruction parameters in display
- [ ] Add Load/Save options for simulation and reconstruction parameters

**Comment by cncastillo** [comment]
I believe this is missing some points from a list I gave you with comments from @pabloirarrazaval.
